In [33]:
import pandas as pd
import matplotlib.pyplot as plt

def load_data(filename):
    df = pd.read_csv(filename,sep=',',header=96)
    df = df.rename(columns={"foo": "bar"})
    return df


df= load_data('exoplanete.csv')

yofu = df[["disc_year","discoverymethod"]].groupby("discoverymethod").min() #year of first use, method by method
nou = df[["pl_name","discoverymethod"]].groupby("discoverymethod").count() #number of use, method by method

methods = pd.merge(left=yofu,left_index=True,right=nou,right_index=True)
methods.columns = ['first use','number of use']

                               first use  number of use
discoverymethod
Astrometry                          2013              3
Disk Kinematics                     2019              1
Eclipse Timing Variations           2009             23
Imaging                             2004            131
Microlensing                        2004            617
Orbital Brightness Modulation       2011             20
Pulsar Timing                       1992             12
Pulsation Timing Variations         2007              2
Radial Velocity                     1995           2465
Transit                             2002          31710
Transit Timing Variations           2011            131